//! Compiles `i18n/*.json` into static Rust tables.
//!
//! Translators edit flat JSON; the firmware gets `&'static str` arrays in
//! flash. Nothing is parsed at runtime -- on a 32 KB part a JSON reader would
//! cost more RAM than the entire shell.
//!
//! English is the reference. If any other language is missing a key, or adds
//! one English does not have, the build fails: a half-translated UI should not
//! be something you discover on the hardware.
//!
//! The parser handles exactly what these files use -- a flat object of string
//! keys to string values, with `\" \\ \n \t` escapes. Keys beginning with `_`
//! are comments and are skipped.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::Path;

/// Languages, in the order the runtime indexes them.
const LANGS: &[(&str, &str)] = &[("EN", "en.json"), ("RO", "ro.json")];

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("strings.rs");

    let mut tables: Vec<(String, BTreeMap<String, String>)> = Vec::new();
    for (name, file) in LANGS {
        let path = format!("i18n/{file}");
        println!("cargo:rerun-if-changed={path}");
        let text = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("cannot read {path}: {e}"));
        tables.push((name.to_string(), parse_flat_json(&text, &path)));
    }

    // English defines the key set and the ordering.
    let keys: Vec<String> = tables[0].1.keys().cloned().collect();

    for (name, map) in &tables[1..] {
        for k in &keys {
            if !map.contains_key(k) {
                panic!("i18n: language {name} is missing key \"{k}\"");
            }
        }
        for k in map.keys() {
            if !tables[0].1.contains_key(k) {
                panic!("i18n: language {name} has key \"{k}\" that EN does not");
            }
        }
    }

    let mut out = String::new();
    out.push_str("// GENERATED by build.rs from i18n/*.json -- do not edit.\n\n");

    out.push_str("/// One translatable message.\n");
    out.push_str("#[derive(Clone, Copy, PartialEq, Eq)]\n#[repr(u16)]\npub enum Msg {\n");
    for (i, k) in keys.iter().enumerate() {
        out.push_str(&format!("    /// `{}`\n    {} = {},\n", k, variant(k), i));
    }
    out.push_str("}\n\n");

    out.push_str(&format!("pub const MSG_COUNT: usize = {};\n", keys.len()));
    out.push_str(&format!("pub const LANG_COUNT: usize = {};\n\n", LANGS.len()));

    out.push_str("pub static LANG_NAMES: [&str; LANG_COUNT] = [");
    for (name, _) in LANGS {
        out.push_str(&format!("\"{name}\", "));
    }
    out.push_str("];\n\n");

    // Language-major, so message `m` of language `l` is entry `l * MSG_COUNT + m`.
    let mut values: Vec<&str> = Vec::new();
    for (_, map) in &tables {
        for k in &keys {
            values.push(&map[k]);
        }
    }
    out.push_str(&pack(&values));

    fs::write(&dest, out).unwrap();
    println!("cargo:rerun-if-changed=build.rs");
}

/// Byte-pair encoding of the whole string table.
///
/// The tables were 45% of the firmware, which is a lot of flash to spend on
/// English and Romanian prose that mostly repeats itself. Every message is
/// rewritten over an alphabet of the byte values it actually uses, and every
/// value above that alphabet is a *code* standing for a pair of symbols --
/// which may themselves be codes, so a single byte can expand to a whole word.
///
/// The codes are chosen greedily: count every adjacent pair in the corpus,
/// give the commonest one a code, substitute it everywhere, and repeat until
/// the byte values run out. A pair seen fewer than three times is left alone,
/// because a code saves one byte per use and costs two in the book.
///
/// This is deliberately not Huffman on top, which was measured and gained
/// 3.2 KB for a bit-level decoder, nor an escape byte for a wider code space,
/// which gained 254 bytes. Neither paid for itself.
fn pack(values: &[&str]) -> String {
    // The alphabet is whatever bytes the corpus actually contains -- 90 of
    // them, as it happens, since both languages are written without
    // diacritics. Everything above it is free for codes. Deriving it rather
    // than assuming ASCII means a translation that does use diacritics still
    // builds; it just gets fewer codes to play with.
    let mut seen = [false; 256];
    for v in values {
        for b in v.bytes() {
            seen[b as usize] = true;
        }
    }
    let alphabet: Vec<u8> = (0..=255u8).filter(|b| seen[*b as usize]).collect();
    let nlit = alphabet.len();
    assert!(nlit < 256, "i18n: no byte values left over for codes");
    let mut to_sym = [0u8; 256];
    for (i, b) in alphabet.iter().enumerate() {
        to_sym[*b as usize] = i as u8;
    }

    let raw: usize = values.iter().map(|v| v.len()).sum();
    let mut syms: Vec<Vec<u8>> = values
        .iter()
        .map(|v| v.bytes().map(|b| to_sym[b as usize]).collect())
        .collect();

    let mut book: Vec<[u8; 2]> = Vec::new();
    let mut counts = vec![0u32; 256 * 256];
    for code in nlit..256 {
        counts.iter_mut().for_each(|c| *c = 0);
        for s in &syms {
            for w in s.windows(2) {
                counts[w[0] as usize * 256 + w[1] as usize] += 1;
            }
        }
        let (best, n) = counts
            .iter()
            .enumerate()
            .max_by_key(|(_, n)| **n)
            .map(|(i, n)| (i, *n))
            .unwrap();
        if n < 3 {
            break;
        }
        let (a, b) = ((best / 256) as u8, (best % 256) as u8);
        book.push([a, b]);
        let code = code as u8;
        for s in syms.iter_mut() {
            let mut outs = Vec::with_capacity(s.len());
            let mut i = 0;
            while i < s.len() {
                if i + 1 < s.len() && s[i] == a && s[i + 1] == b {
                    outs.push(code);
                    i += 2;
                } else {
                    outs.push(s[i]);
                    i += 1;
                }
            }
            *s = outs;
        }
    }

    let mut packed: Vec<u8> = Vec::new();
    let mut spans: Vec<usize> = vec![0];
    for s in &syms {
        packed.extend_from_slice(s);
        spans.push(packed.len());
    }
    assert!(
        packed.len() <= u16::MAX as usize,
        "i18n: {} packed bytes will not fit a u16 span table -- widen SPANS to u32",
        packed.len()
    );

    // Decode it all back and compare. A compressor that is wrong about one
    // string in a thousand is worse than no compressor, and the only other
    // place that would show up is a garbled line on the hardware. This also
    // measures the decode stack rather than reasoning about it: the runtime
    // sizes its stack from DEPTH, and `forbid(unsafe_code)` means guessing low
    // would be a panic on the board.
    let mut depth = 1usize;
    for (i, want) in values.iter().enumerate() {
        let (got, d) = unpack(&packed[spans[i]..spans[i + 1]], &alphabet, &book);
        assert_eq!(
            got.as_slice(),
            want.as_bytes(),
            "i18n: entry {i} does not survive the round trip"
        );
        depth = depth.max(d);
    }

    let total = packed.len() + book.len() * 2 + nlit + spans.len() * 2;
    let mut out = String::new();
    out.push_str(&format!(
        "\n// Packed with byte-pair encoding: {raw} bytes of text in {} strings\n\
         // became {} packed + {} book + {nlit} alphabet + {} spans = {total} \
         ({:.1}% of the original).\n\n",
        values.len(),
        packed.len(),
        book.len() * 2,
        spans.len() * 2,
        100.0 * total as f64 / raw as f64,
    ));
    out.push_str(&format!(
        "/// Byte values the corpus uses. A symbol below this many is a literal.\n\
         pub const NLIT: u8 = {nlit};\n\n\
         /// Deepest a code nests, and so how much decode stack an expansion needs.\n\
         pub const DEPTH: usize = {depth};\n\n"
    ));
    out.push_str(&format!("pub static ALPHABET: [u8; {nlit}] = ["));
    for b in &alphabet {
        out.push_str(&format!("{b},"));
    }
    out.push_str("];\n\n");

    out.push_str("/// Each code expands to two symbols, which may be codes in turn.\n");
    out.push_str(&format!("pub static BOOK: [[u8; 2]; {}] = [", book.len()));
    for [a, b] in &book {
        out.push_str(&format!("[{a},{b}],"));
    }
    out.push_str("];\n\n");

    out.push_str(&format!(
        "/// Where each entry starts in [`PACKED`]; the extra last one ends it.\n\
         pub static SPANS: [u16; {}] = [",
        spans.len()
    ));
    for s in &spans {
        out.push_str(&format!("{s},"));
    }
    out.push_str("];\n\n");

    out.push_str("pub static PACKED: [u8; ");
    out.push_str(&format!("{}] = *b\"", packed.len()));
    for b in &packed {
        match b {
            b'\\' => out.push_str("\\\\"),
            b'"' => out.push_str("\\\""),
            0x20..=0x7e => out.push(*b as char),
            _ => out.push_str(&format!("\\x{b:02x}")),
        }
    }
    out.push_str("\";\n");
    out
}

/// The runtime decoder, kept honest by running it at build time.
///
/// Returns the text and the deepest the pending-symbol stack got.
fn unpack(packed: &[u8], alphabet: &[u8], book: &[[u8; 2]]) -> (Vec<u8>, usize) {
    let nlit = alphabet.len();
    let mut out = Vec::new();
    let mut stack: Vec<u8> = Vec::new();
    let mut deepest = 0;
    let mut at = 0;
    loop {
        let mut sym = match stack.pop() {
            Some(s) => s,
            None if at < packed.len() => {
                at += 1;
                packed[at - 1]
            }
            None => break,
        };
        // Walk down the left of the tree, saving each right branch for later.
        while (sym as usize) >= nlit {
            let [a, b] = book[sym as usize - nlit];
            stack.push(b);
            deepest = deepest.max(stack.len());
            sym = a;
        }
        out.push(alphabet[sym as usize]);
    }
    (out, deepest)
}

/// `post.cpu` -> `PostCpu`
fn variant(key: &str) -> String {
    let mut s = String::new();
    let mut upper = true;
    for c in key.chars() {
        if c == '.' || c == '_' || c == '-' {
            upper = true;
        } else if upper {
            s.extend(c.to_uppercase());
            upper = false;
        } else {
            s.push(c);
        }
    }
    s
}

/// Minimal reader for a flat `{"key": "value"}` object.
fn parse_flat_json(text: &str, path: &str) -> BTreeMap<String, String> {
    let b: Vec<char> = text.chars().collect();
    let mut i = 0usize;
    let mut map = BTreeMap::new();

    let skip_ws = |i: &mut usize| {
        while *i < b.len() && b[*i].is_whitespace() {
            *i += 1;
        }
    };

    // Reads a JSON string starting at the opening quote.
    let read_str = |i: &mut usize| -> String {
        assert_eq!(b[*i], '"', "{path}: expected a string at char {i}");
        *i += 1;
        let mut s = String::new();
        while *i < b.len() && b[*i] != '"' {
            if b[*i] == '\\' {
                *i += 1;
                match b[*i] {
                    'n' => s.push('\n'),
                    't' => s.push('\t'),
                    'r' => s.push('\r'),
                    c => s.push(c), // covers \" and \\
                }
            } else {
                s.push(b[*i]);
            }
            *i += 1;
        }
        *i += 1; // closing quote
        s
    };

    skip_ws(&mut i);
    assert_eq!(b[i], '{', "{path}: expected '{{' at the start");
    i += 1;

    loop {
        skip_ws(&mut i);
        if i >= b.len() || b[i] == '}' {
            break;
        }
        if b[i] == ',' {
            i += 1;
            continue;
        }
        let key = read_str(&mut i);
        skip_ws(&mut i);
        assert_eq!(b[i], ':', "{path}: expected ':' after key \"{key}\"");
        i += 1;
        skip_ws(&mut i);
        let val = read_str(&mut i);

        // A raw newline inside a value is always an editing accident -- an
        // escape that was written as one character instead of two. It renders
        // as a stray line break on the board, which is a slow way to find out.
        if let Some(bad) = val.chars().find(|c| *c == '\r' || (c.is_control() && *c != '\n' && *c != '\t')) {
            panic!(
                "{path}: value for \"{key}\" contains a raw control character \
                 {bad:?} -- write it as an escape (\\n, \\t) rather than \
                 embedding it"
            );
        }

        if !key.starts_with('_') {
            if map.insert(key.clone(), val).is_some() {
                panic!("{path}: duplicate key \"{key}\"");
            }
        }
    }
    map
}
